### ISSUE TITLE
In self-service portal, allow drivers and to add notes next to add notes next to confirmed matches

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/backend#129]
Next to each confirmed match in the self-service portal (for drivers and riders), add a box that lets drivers/riders record notes for themselves.

This is especially useful for drivers, to keep track if they're arranging multiple rides.

**Comment by dmilet** [comment]
working on the db side of it, will post back later

**Comment by jkbits1** [comment]
@sasjkia I'm just taking a look at this as you thought it is something that one of the new contributors can help with. Do you have any thoughts (or mock up) of how the UI will look and work for this? Currently, for each match there is a Cancel button. As well as a textbox, is the plan to add an Add Notes button for each match? That button will end up being reasonably close to the Cancel button, only so much that can be done to avoid that

**Comment by sasjkia** [comment]
@jkbits1 this is a very crude mockup created in my Open Office 🥇 Obvs colours, text, style should reflect Carpool Vote standard. But this is the general principle. I can try to get a UX person to do a proper mockup if needed. Let me know!

![image](https://cloud.githubusercontent.com/assets/19363959/26038137/62335934-38cf-11e7-948f-0b78bfb3ac08.png)

**Comment by sasjkia** [comment]
@kylejcrawford

**Comment by kylejcrawford** [comment]
@sasjkia A few initial questions:

- To what extent do we know drivers are looking for something like this?  Because they will be communicating with riders via a separate platform (either SMS or email), how likely is it that they log back into the portal in order to add notes? Might they track ride order another way (like just adding each person at certain times on their calendar)?

If it is expected they'll use it sufficiently enough to build it, then I'd suggest we look for a more subtle way to include the feature than a full text box. One reason is that if a driver has multiple riders, the screen will be cluttered with text boxes.

**Comment by jkbits1** [comment]
@sasjkia the new operator focus of the system means this issue is less of a priority, but it's not so hard to do so I'll add a low priority label
