### ISSUE TITLE
Remove rider identifying details (name, contact details) from proposed matches in self-service portal

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/backend#140]
This should only become visible once match has been accepted.

**Comment by sasjkia** [comment]
For data protection reasons, this is high priority. Thanks! :)

**Comment by jkbits1** [comment]
@sasjkia can we quickly review which to remove and which to keep, please?

Definite removals - rider name, rider phone, rider email. 

However, what about the following :
rider collection - this currently is the zip code plus the address. Presumably address is to be removed, but not the zip?
rider drop off - same question as for rider collection
rider contact method, notes - currently both preferred contact method and any specific notes are shown. Do we keep either or both of these?

**Comment by sasjkia** [comment]
@jkbits1  - hassan proposed a solution to strip only the street/apartment numbers from the address but keep the street name as well as zip: https://github.com/datamade/usaddress

**Comment by sasjkia** [comment]
@jkbits1 - hassan schroeder proposed a resource to remove the apartment number and street number but keep the street name and zip: https://github.com/datamade/usaddress

this would be better because zip codes can be pretty big in some places.

**Comment by jkbits1** [comment]
@sasjkia thanks for the feedback. On this page, the node app provides the zip and address as separate fields, so there is no processing to be done. It's easy to remove the address and show the zip only. 

The same applies to the contact method and notes, it's straightforward to display either of these on their own if we want to do that.

**Comment by jkbits1** [comment]
@sasjkia thanks for this. That sort of complex processing of the address is not possible for an immediate fix. Hassan's suggestion is a Python library, so it doesn't naturally blend in with either the node app or the browser, which both use JS. 

We can either leave this open and involve Richard on processing the address, or make some immediate changes based on the information currently provided to the browser page then provide a more subtle improvement later

**Comment by sasjkia** [comment]
@jkbits1 i thing this brings us back to the point that this could be a frontend issue. i suggested that we split the apt name and street number at user input stage. we shouild have a new ux person starting next week. i suggest we see what they say.

**Comment by jkbits1** [comment]
@sasjkia Fine. I've removed the high priority tag and added a Pending review tag

**Comment by sasjkia** [comment]
@kylejcrawford do you have any thoughts on a frontend solution for this?

**Comment by kylejcrawford** [comment]
It seems like the potential for confusion or bad matches is stemming from too vague of information at the driver signup. And that is coming to light and causing ambiguity at the match detail stage. So rather than the driver inputting a zip code and mileage radius as the criteria for rides (current state), it seems like they should be inputting address and mileage radius. Then, as long as we can calculate the distance between the driver address and rider pickup address on the backend as part of the match criteria, we wouldn't need to disclose rider details early on or deal with the possibility that rides are too far away in the same zip code. We could just confidently tell the driver somebody matches their criteria, and give the requested time of the ride so they could schedule it in. Then, like you all proposed, the rest of the specifics can be shared after the ride is accepted. Thoughts/issues?

**Comment by sasjkia** [comment]
Whilst we wait to find a solution for the address, please can we still remove the rider's name, email, phone number from the initial notification?

**Comment by sasjkia** [comment]
@kylejcrawford the issue re confusion has been addressed by tweaking the flexibility in the matching algorithm. I think we should leave the zip+radius feature as is for now.

**Comment by jkbits1** [comment]
@sasjkia now this has been agreed, will change this
