### ISSUE TITLE
Driver self-service portal doesn't update immediately when a driver accepts a match

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/backend#146]
When a driver accepts a match, they receive a notification of the confirmed match.

However, the self-service portal doesn't update until they have logged out and logged back in again. This can get confusing for the driver, as it may not be clear to them whether or not they have actually confirmed the match.

When the driver confirms a match in the self-service portal, please create a fix so that the match moves straight to the **Driver confirmed matches** section.

**Comment by jkbits1** [comment]
@sasjkia this relates to this https://github.com/voteamerica/voteamerica.github.io/issues/283 This functionality did exist, but was broken due to db changes

I've assigned myself to fix it

**Comment by jkbits1** [comment]
@sasjkia I’m working on fixing this now. This issue, also 
https://github.com/voteamerica/voteamerica.github.io/issues/283
https://github.com/voteamerica/voteamerica.github.io/issues/263
https://github.com/voteamerica/voteamerica.github.io/issues/257
occurred due to unilateral changes to the db code/node app made without sufficient testing of their impact.

It is exactly due to this and similar situations that I have been working to create the automated test setup. Currently this setup supports tests that add a rider and driver and confirm these have been added successfully. Over the next couple of weeks, the setup will be extended to basic checks of the self-service page.

At the moment, the automated test setup will not prevent unilateral code changes that break the system (I have some ideas for that, too), but it will enable us to be aware of the situation earlier and know the extent of the problems caused.
