### ISSUE TITLE
Clicking "Cancel drive offer" button in self-service portal results in funny text but no indication that the offer has been cancelled

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/backend#165]

**Comment by jkbits1** [comment]
@sasjkia if at all possible, details of the "funny text" are very helpful in reproducing the issue 😄 this issue is part of https://github.com/voteamerica/voteamerica.github.io/issues/258. The cancellation has worked, and the driver is no longer shown either proposed or confirmed matches.

It's a good point about the lack of indication 👍 I'll add something to the driver info to show when their status is cancelled

**Comment by sasjkia** [comment]
![image](https://user-images.githubusercontent.com/19363959/26848582-f3185d44-4ace-11e7-80f2-ae3405def3c3.png)

**Comment by sasjkia** [comment]
that's the funny text :D

**Comment by jkbits1** [comment]
thanks 😄 that's the funny text I first thought of, but couldn't reproduce. This should be something that I've fixed recently.

I've checked just now on the test system and the behaviour is the cryptic behaviour in the issue mentioned above, not the funny text 😄 . The test system has recently been updated, so that might explain the difference.

Or is this a live system thing? Either way, I'll make the cancellation more clear as my next task
