### ISSUE TITLE
node index.js should generate UUID outside of INSERT

### ISSUE THREAD

**Issue by dmilet** [voteamerica/backend#24]
Need to generate UUID (v4) outside of INSERT, so we have it available to send notification back to submitter.
https://blog.tompawlak.org/generate-unique-identifier-nodejs-javascript

I added UUID columns as 
 UUID             | character varying(50)       | not null default gen_random_uuid()

However, the default value should not be used, unless we do bulk load of data

**Comment by jkbits1** [comment]
The referenced PR addresses this issue. If it resolves it completely, we can close this, or otherwise leave it open for further discussion

**Comment by dmilet** [comment]
Hi, I saw index.js code earlier that seemed to work fine retrieving after insert, the uuid as assigned by the db
So maybe we don't need to generate the uuid outside of insert after all?
I don't know what's best, but somehow I feel it's more efficient to have the uuid generated by the app locally, because it would require a db call to retrieve the data after the insert is completed. Also, if insert fails, we don't get to see the uuid in the log
At work, I always have my app generate id's before the insert.
What's your view on this?


What do you think is best?

**Comment by jkbits1** [comment]
I definitely see your point of view. In this case, I'm quite positive about using the default UUID. The returning clause (as part of the insert) brings back the uuid as a part of a single action, so it's not an insert then a query. The db call is already synchronous so that the client knows if it succeeded, so the pattern is the same.

If the uuid is generated by Postgres, we don't have to concern ourselves with a check on the quality of the library used by the app. 

I see your point about the client not having a uuid returned to them. I was looking through the logs today, though, and all the contact info is there for a failed insert.

I'm fairly relaxed how we do it, though. It can always be refactored later (depending on what we want to do with returning a value to the client).

**Comment by dmilet** [comment]
Issue can be closed
