### ISSUE TITLE
Incomplete nov2016.zip_codes table

### ISSUE THREAD

**Issue by dmilet** [voteamerica/backend#52]
There are only 33k zip codes out of approx 43k.
Need to find more comprehensive source

**Comment by misteranderson** [comment]
So, just to give some context, there are approx. 9K "PO BOX" zip codes.  The initial load of data didn't appear to contain those values.  Additionally, it was admittedly an older dataset., so there may be some newer "Standard" ZIP Cods which were added after the dataset was compiled.  We have purchased a copy of recent data from a supplier, and I'll be loading that data into the existing table to fill in the gaps.

**Comment by dmilet** [comment]
@misteranderson if you could  load it on carpool_v2.0_live and carpool_v2,0_test that would be great!
I'll get a dump from one of them to include in the fresh db creation script.

**Comment by dmilet** [comment]
What is the plan for the missing latitude/longitude coordinates for the 10,050 zip  codes that were added ?
Now the zip code can be found (so the user records don't get marked as Failed anymore), but the distances calculated with nov2016.distance() will be NULL, meaning they will never be included in any match. This is more insidious, because the system would appear to work properly, instead of identifying the records as Failed. 

If we can't add the missing lat/lon info into zip_codes quickly, I'll have to modify the matching code to catch this exception too.

**Comment by misteranderson** [comment]
My thought is to use the Google geocoding API to geocode the remaining ZIPs programmatically; There could be a couple of approaches - geocode on demand (if we don't know the info, then look it up and store it back into the DB) - or batch geocode, for a few dollars (exceeding the free API threshold), I can have enough requests to get the remaining ZIPs filled in probably later tonight.

**Comment by misteranderson** [comment]
Turns out, I was able to fix it by just falling back (for now) to the slightly less precise value supplied in the data feed, but I had done my coalesce() wrong on the inintial insert - the data was '' instead of NULL.
Fixing with 


UPDATE nov2016.zip_codes
SET
 latitude  = CAST(  COALESCE(NULLIF(precise_latitude  ,''),src.latitude)  AS character varying(10))
,longitude = CAST(  COALESCE(NULLIF(precise_longitude ,''),src.longitude) AS character varying(10))
,latitude_numeric = CAST( COALESCE(NULLIF(precise_latitude ,''),src.latitude)  AS numeric)
,longitude_numeric= CAST( COALESCE(NULLIF(precise_longitude,''),src.longitude) AS numeric)
FROM
import.zip_code_database_commercial as src
WHERE
nov2016.zip_codes.zip = src.zip
;

**Comment by misteranderson** [comment]
Please let me know if this is now resolved.  

At the same time, in the test db, I brought in the TimeZone as well..

carpool_v2.0_test=# alter table nov2016.zip_codes add column timezone character varying(50) null default '';
ALTER TABLE
carpool_v2.0_test=# UPDATE nov2016.zip_codes
carpool_v2.0_test-# SET
carpool_v2.0_test-# timezone = src.timezone from 
carpool_v2.0_test-# import.zip_code_database_commercial as src
carpool_v2.0_test-# WHERE
carpool_v2.0_test-# nov2016.zip_codes.zip = src.zip
carpool_v2.0_test-# ;
UPDATE 42003

**Comment by dmilet** [comment]
Looks good to me.
