### ISSUE TITLE
After POST , redirect URL to use uuid_driver and uuid_rider as needed

### ISSUE THREAD

**Issue by dmilet** [voteamerica/backend#73]
I think it needs a change in the node app

**Comment by jkbits1** [comment]
what's the context of this issue? the redirect urls are provided by client

**Comment by misteranderson** [comment]
The client does need an update, the current version has the _redirect variable reversed, so riders are sent to the thanks-driver page, and drivers as sent to the thanks-rider page.  Will open an issue on the other repo.

**Comment by jkbits1** [comment]
@dmilet @misteranderson just looking at the code, I see that I do add the uuid on the end of the redirect. At the moment the node app adds `"?uuid="` plus the value itself. It would be easiest, and keep the code simple, if the node app only had to add the value. I can change and test the front-end if necessary to ensure everything lines up

**Comment by richardwestenra** [comment]
@jkbits1 @dmilet @misteranderson  I mentioned this [elsewhere](https://github.com/voteamerica/voteamerica.github.io/issues/185#issuecomment-256594374), but on reflection, seeing as we're already using the UUID key, I'd recommend simply adding a `type` key and setting it to either `driver` or `rider` (e.g. http://carpoolvote.com/thanks-driver/?uuid=b409c43a-b581-4a5c-831d-339c1783c8a9&type=rider). This wouldn't necessarily require any immediate backend change on the redirects, because I can do this on the front end in the thank you pages. However it would be useful to add it in the form redirects as a backup, and especially in the emails.
Thoughts?

**Comment by jkbits1** [comment]
@richardwestenra I'm short on time to review this closely but that sounds valid. at the moment, the node app takes the redirect string and adds the uuid number to it. so if you send the link you suggest but change the order of the params i.e. http://carpoolvote.com/thanks-driver/?type=rider&uuid=b409c43a-b581-4a5c-831d-339c1783c8a9 then that will work as the system is now, and we don't need to change and redeploy the node app

**Comment by richardwestenra** [comment]
@jkbits1 Nice, good call :) Thanks!

**Comment by dmilet** [comment]
This issue is fixed on the new system
